apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: appnamespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: appnamespace
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: appnamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: appnamespace
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: appnamespace
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: appnamespace
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.12.2
          args:
            - --source=service # ingress is also possible
            - --domain-filter=aurin-prod.cloud.edu.au # (optional) limit to only example.com domains; change to match the zone created above.
            - --provider=designate
          env: # values from openrc file
            - name: OS_AUTH_URL
              value: https://keystone.rc.nectar.org.au:5000/v3/
            - name: OS_REGION_NAME
              value: Melbourne
            - name: OS_AUTH_TYPE
              value: v3applicationcredential
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_APPLICATION_CREDENTIAL_ID
              value: $OS_APPLICATION_CREDENTIAL_ID
            - name: OS_APPLICATION_CREDENTIAL_SECRET
              value: $OS_APPLICATION_CREDENTIAL_SECRET